name: Actions with variable 

on: 
  workflow_dispatch:

env:
  FIRST_NAME: mona

jobs:
  my_first_job:
    env:
      LAST_NAME: Darling
    name: my first job
    runs-on: ubuntu-slim
    steps:
     - name: Checkout
       uses: actions/checkout@v6.0.3

     - name: Greetings
       run: echo "Hello, $FIRST_NAME $LAST_NAME!"
      
