name: Hello World Workflow
on: workflow_dispatch

jobs:
  my_first_job: 
    name: My first job
    runs-on: ubuntu-slim
    steps:
     - name: Greeting
       run: echo "Hello world from Linux runner Github Action worklflow"
       
  my_second_job:     
   name: My second job
   runs-on: windows-latest
   steps:
     - name: windows
       run: echo "Hello world from Windows runner Github Action worklflow"
      
    
